version: "3.9"
name: "parra-ecommerce-application"

services:
  ecommerce-database:
    image: "mysql:8.3"
    command: --default-authentication-plugin=mysql_native_password
    container_name: ecommerce-data-store
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    labels:
      org.springframework.boot.service-connection: mysql
    networks:
      app-network:
        ipv4_address: 172.28.0.30
        aliases:
          - "ecommerce-data"
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254