server:
  port: 80
spring:
  application:
    name: login-ecommerce-with-spring
  datasource:
    url: "jdbc:mysql://ecommerce-database/ecommerce"
    username: "ecommerce"
    password: "password123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true