server:
  port: 80
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: ALWAYS
    include-stacktrace: ALWAYS
spring:
  docker:
    compose:
      file: "docker-compose.yml"
      lifecycle-management: start-and-stop
  application:
    name: login-ecommerce-with-spring
  datasource:
    url: "jdbc:mysql://ecommerce-database/ecommerce"
    username: "ecommerce"
    password: "password123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true